name: 'DigitalOcean Registry Cleanup Action'
description: 'Deletes tags older than a specified number of days from a DigitalOcean container registry'
author: 'Mrugesh Mohapatra'
branding:
  icon: 'trash'
  color: 'red'
inputs:
  repository_name:
    description: 'Name of the DigitalOcean container registry repository'
    required: true
  dry_run:
    description: 'If set to true, it will display tags to be deleted without actually deleting them'
    required: false
    default: 'false'
  days:
    description: 'Number of days. Tags older than these many days will be deleted'
    required: false
    default: '2'

runs:
  using: 'composite'
  steps:
    - run:  $GITHUB_ACTION_PATH/entrypoint.sh ${{ inputs.dry_run == 'true' && '-d' || '' }} -n ${{ inputs.days }} ${{ inputs.repository_name }} 
      shell: bash
